services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crescendo-frontend-dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./angular.json:/app/angular.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
    networks:
      - crescendo-dev

  nginx:
    image: nginx:alpine
    container_name: crescendo-nginx-dev
    ports:
      - "85:85"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./dist/crescendo/browser:/usr/share/nginx/html
    depends_on:
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - crescendo-dev

networks:
  crescendo-dev:
    driver: bridge
